version: '3.1'

services:
  # Database
  complete_backend_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $MASTER_DATABASE_PASS
      POSTGRES_DB: $MASTER_DATABASE_NAME
    ports:
      - "${MASTER_DATABASE_PORT}:5432"

  # Cache
  redis:
    image: redis:7.0.8
    container_name: bsc_dex_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
